export const SAVE_GLOBALS = "SAVE_GLOBALS";
export const UPDATE_ALERT = "UPDATE_ALERT"
export const DISCOUNT_TIMMER = "DISCOUNT_TIMMER"
export const UPDATE_ISSUES_APPLIANCE_BRANDS = "UPDATE_ISSUES_APPLIANCE_BRANDS"
export const SHOW_THANKYOU = "SHOW_THANKYOU"